"""Generated IANA SvcParamKey registry data; do not edit by hand."""

# Generated by `python -m src.registry_codegen --write`.

IANA_REGISTRY_METADATA: dict[str, str] = {
    "schema_version": "1",
    "registry_id": "dns-svcparamkeys",
    "registry_name": "DNS SVCB Service Parameter Keys (SvcParamKeys)",
    "registry_page_url": "https://www.iana.org/assignments/dns-svcb/dns-svcb.xhtml",
    "csv_url": "https://www.iana.org/assignments/dns-svcb/dns-svcparamkeys.csv",
    "iana_last_updated": "2026-06-25",
    "retrieved_at": "2026-07-10",
    "payload_file": "dns-svcparamkeys-2026-06-25.csv.b64",
    "payload_encoding": "base64",
    "payload_length": "1264",
    "payload_sha256": "2a1695a17ab72f36585d166efb9eda2c911d547158a8963adf7914df74de9231",
}

IANA_SVCPARAM_REGISTRY: dict[int, dict[str, str]] = {
    0: {
        "name": "mandatory",
        "meaning": "Mandatory keys in this RR",
        "change_controller": "IETF",
        "reference": "[RFC9460, Section 8]",
    },
    1: {
        "name": "alpn",
        "meaning": "Additional supported protocols",
        "change_controller": "IETF",
        "reference": "[RFC9460, Section 7.1]",
    },
    2: {
        "name": "no-default-alpn",
        "meaning": "No support for default protocol",
        "change_controller": "IETF",
        "reference": "[RFC9460, Section 7.1]",
    },
    3: {
        "name": "port",
        "meaning": "Port for alternative endpoint",
        "change_controller": "IETF",
        "reference": "[RFC9460, Section 7.2]",
    },
    4: {
        "name": "ipv4hint",
        "meaning": "IPv4 address hints",
        "change_controller": "IETF",
        "reference": "[RFC9460, Section 7.3]",
    },
    5: {
        "name": "ech",
        "meaning": "TLS Encrypted ClientHello Config",
        "change_controller": "IETF",
        "reference": "[RFC9848]",
    },
    6: {
        "name": "ipv6hint",
        "meaning": "IPv6 address hints",
        "change_controller": "IETF",
        "reference": "[RFC9460, Section 7.3]",
    },
    7: {
        "name": "dohpath",
        "meaning": "DNS over HTTPS path template",
        "change_controller": "IETF",
        "reference": "[RFC9461]",
    },
    8: {
        "name": "ohttp",
        "meaning": "Denotes that a service operates an Oblivious HTTP target",
        "change_controller": "IETF",
        "reference": "[RFC9540, Section 4]",
    },
    9: {
        "name": "tls-supported-groups",
        "meaning": "Supported groups in TLS",
        "change_controller": "IETF",
        "reference": "[draft-ietf-tls-key-share-prediction-01, Section 3.1]",
    },
    10: {
        "name": "docpath",
        "meaning": "DNS over CoAP resource path",
        "change_controller": "IETF",
        "reference": "[RFC9953, Section 3]",
    },
    11: {
        "name": "pvd",
        "meaning": "PvD configuration is available at the well-known path",
        "change_controller": "IETF",
        "reference": "[RFC-ietf-intarea-proxy-config-13, Section 2.1]",
    },
    12: {
        "name": "oots",
        "meaning": (
            "Per-transport operator confidence in serving the \nnameserver's query "
            "load over that transport, as a percentage"
        ),
        "change_controller": "IETF",
        "reference": "[draft-johani-dnsop-svcb-oots-00, Section 5]",
    },
}

IANA_SVCPARAM_SPECIAL_RANGES: tuple[dict[str, int | str], ...] = (
    {
        "start": 13,
        "end": 65279,
        "name": "Unassigned",
        "meaning": "",
        "change_controller": "",
        "reference": "",
    },
    {
        "start": 65280,
        "end": 65534,
        "name": "N/A",
        "meaning": "Reserved for Private Use",
        "change_controller": "IETF",
        "reference": "[RFC9460]",
    },
    {
        "start": 65535,
        "end": 65535,
        "name": "N/A",
        "meaning": 'Reserved ("Invalid key")',
        "change_controller": "IETF",
        "reference": "[RFC9460]",
    },
)
